version: '3.4'
services:
  qrljs:
    build:
      context: .
      dockerfile: ../Dockerfile
    container_name: qrljs
    volumes:
      - ./datadir:/datadir
    command: >
      --dataDir=/datadir
    network_mode: host
