name: VM
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      dep-cache-key:
        required: false
        default: 'none'

env:
  cwd: ${{github.workspace}}/packages/vm

defaults:
  run:
    working-directory: packages/vm

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-vm
  cancel-in-progress: true

jobs:
  test-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - if: inputs.dep-cache-key != 'none'
        uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install Dependencies (if not restored from cache)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ${{ github.workspace }}

      - run: npm run coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: vm
